const {
  PUBLIC_STELLAR_NETWORK: STELLAR_NETWORK,
  PUBLIC_STELLAR_NETWORK_PASSPHRASE: STELLAR_NETWORK_PASSPHRASE,
  PUBLIC_STELLAR_RPC_URL: STELLAR_RPC_URL,
  PUBLIC_STELLAR_HORIZON_URL: STELLAR_HORIZON_URL,
  PUBLIC_STELLAR_FRIENDBOT_URL: STELLAR_FRIENDBOT_URL,
} = import.meta.env;

export {
  STELLAR_NETWORK,
  STELLAR_NETWORK_PASSPHRASE,
  STELLAR_RPC_URL,
  STELLAR_HORIZON_URL,
  STELLAR_FRIENDBOT_URL,
};
